### ISSUE TITLE
Error compiling on Ubuntu 20.04

### ISSUE THREAD

**Issue by emmanuelkring** [stack-of-tasks/eigenpy#179]
Hello, I am trying to compile on Ubuntu 20.04 with noetic and I get this error:
>/usr/include/boost/python/detail/destroy.hpp:20:9: error: ‘Eigen::MatrixBase<Derived>::~MatrixBase() [with Derived = Eigen::Matrix<double, -1, 1>]’ is protected within this context
   20 |         p->~T();
      |         ^
In file included from /usr/include/eigen3/Eigen/Core:88,
                 from /home/emmanuel/moveit_ws/src/eigenpy/src/decompositions/decompositions.cpp:6:
/usr/include/eigen3/Eigen/src/Core/MatrixBase.h:468:5: note: declared protected here
  468 |     EIGEN_DEFAULT_EMPTY_CONSTRUCTOR_AND_DESTRUCTOR(MatrixBase)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/eigenpy.dir/build.make:92: CMakeFiles/eigenpy.dir/src/decompositions/decompositions.cpp.o] Error 1

If I change protected to public in /usr/include/eigen3/Eigen/src/Core/MatrixBase.h I get the additional error: 
>/usr/include/boost/python/detail/destroy.hpp:20:9: error: ‘Eigen::QuaternionBase<Derived>::~QuaternionBase() [with Derived = Eigen::Quaternion<double>]’ is protected within this context
   20 |         p->~T();
      |         ^
In file included from /usr/include/eigen3/Eigen/Core:88,
                 from /home/emmanuel/moveit_ws/src/eigenpy/include/eigenpy/fwd.hpp:11,
                 from /home/emmanuel/moveit_ws/src/eigenpy/include/eigenpy/quaternion.hpp:9,
                 from /home/emmanuel/moveit_ws/src/eigenpy/src/quaternion.cpp:8:
/usr/include/eigen3/Eigen/src/Geometry/Quaternion.h:188:3: note: declared protected here
  188 |   EIGEN_DEFAULT_EMPTY_CONSTRUCTOR_AND_DESTRUCTOR(QuaternionBase)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/eigenpy.dir/build.make:261: CMakeFiles/eigenpy.dir/src/quaternion.cpp.o] Error 1

**Comment by nim65s** [comment]
FYI, this can be easily reproduced with `docker run --rm -it gepetto/utils:eigenpy-20.04`. Once in the container, running `make` show this error.

On a side note, this version of ubuntu is not yet available, even if we have been in April 2020 for the last 5min :)

**Comment by nim65s** [comment]
But it works on ArchLinux : `docker run --rm -it gepetto/utils:eigenpy-arch`

|  | 20.04 | Arch |
|-|---------|-------|
| boost | 1.71.0 | 1.72.0 |
| numpy | 1.16.5 | 1.18.2 |
| eigen | 3.3.7 | 3.3.7 |
| gcc | 9.3.0 | 9.3.0 |
| python | 3.8.2 | 3.8.2 |

The Dockerfiles are here: https://github.com/nim65s/gepetto-utils/tree/master/docker/eigenpy

**Comment by jcarpent** [comment]
@emmanuelkring Thanks a lot for raising this future issue.
I've solved it in #180 and thanks to @nim65s's work, I've been able to test it on 20.04. It seems to work fine now.

I will provide a new release then. @emmanuelkring Is it OK for you?
